//
// Module SAYEH_lib.Sayeh.struct
//
// Created:
//          by - Christopher.UNKNOWN (CJ)
//          at - 17:45:27 02/ 7/2012
//
// Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
//

`timescale 1 ns /1 ns
module Sayeh( 
   clk, 
   ReadMem, 
   WriteMem, 
   ReadIO, 
   WriteIO, 
   Databus, 
   Addressbus, 
   ExternalReset, 
   MemDataready
);


// Internal Declarations

input         clk;
output        ReadMem;
output        WriteMem;
output        ReadIO;
output        WriteIO;
inout  [15:0] Databus;
output [15:0] Addressbus;
input         ExternalReset;
input         MemDataready;


wire        clk;
wire        ReadMem;
wire        WriteMem;
wire        ReadIO;
wire        WriteIO;
wire [15:0] Databus;
wire [15:0] Addressbus;
wire        ExternalReset;
wire        MemDataready;

// Local declarations

// Internal signal declarations
//----------------------------------------------------------------------
wire [15:0] Instruction;
wire        ResetPC;
wire        PCplusI;
wire        PCplus1;
wire        RplusI;
wire        Rplus0;
wire        Rs_on_AddressUnitRSide;
wire        Rd_on_AddressUnitRSide;
wire        EnablePC;
wire        B15to0;
wire        AandB;
wire        AorB;
wire        notB;
wire        shlB;
wire        shrB;
wire        AaddB;
wire        AsubB;
wire        AmulB;
wire        AcmpB;
wire        RFHwrite;
wire        RFLwrite;
wire        WPreset;
wire        WPadd;
wire        IRload;
wire        SRload;
wire        Address_on_Databus;
wire        ALU_on_Databus;
wire        IR_on_LOpndBus;
wire        IR_on_HOpndBus;
wire        RFright_on_OpndBus;
wire        Cset;
wire        Creset;
wire        Zset;
wire        Zreset;
wire        Shadow;
wire        Cflag;
wire        Zflag;


// Instances 
DataPath dp( 
   .ALU_on_Databus         (ALU_on_Databus), 
   .AaddB                  (AaddB), 
   .AandB                  (AandB), 
   .AcmpB                  (AcmpB), 
   .Address_on_Databus     (Address_on_Databus), 
   .AmulB                  (AmulB), 
   .AorB                   (AorB), 
   .AsubB                  (AsubB), 
   .B15to0                 (B15to0), 
   .Creset                 (Creset), 
   .Cset                   (Cset), 
   .EnablePC               (EnablePC), 
   .IR_on_HOpndBus         (IR_on_HOpndBus), 
   .IR_on_LOpndBus         (IR_on_LOpndBus), 
   .IRload                 (IRload), 
   .PCplus1                (PCplus1), 
   .PCplusI                (PCplusI), 
   .RFHwrite               (RFHwrite), 
   .RFLwrite               (RFLwrite), 
   .RFright_on_OpndBus     (RFright_on_OpndBus), 
   .Rd_on_AddressUnitRSide (Rd_on_AddressUnitRSide), 
   .ResetPC                (ResetPC), 
   .Rplus0                 (Rplus0), 
   .RplusI                 (RplusI), 
   .Rs_on_AddressUnitRSide (Rs_on_AddressUnitRSide), 
   .SRload                 (SRload), 
   .Shadow                 (Shadow), 
   .WPadd                  (WPadd), 
   .WPreset                (WPreset), 
   .Zreset                 (Zreset), 
   .Zset                   (Zset), 
   .clk                    (clk), 
   .notB                   (notB), 
   .shlB                   (shlB), 
   .shrB                   (shrB), 
   .Addressbus             (Addressbus), 
   .Cout                   (Cflag), 
   .Instruction            (Instruction), 
   .Zout                   (Zflag), 
   .Databus                (Databus)
); 

controller ctrl( 
   .Cflag                  (Cflag), 
   .ExternalReset          (ExternalReset), 
   .Instruction            (Instruction), 
   .Zflag                  (Zflag), 
   .clk                    (clk), 
   .memDataReady           (MemDataready), 
   .ALU_on_Databus         (ALU_on_Databus), 
   .AaddB                  (AaddB), 
   .AandB                  (AandB), 
   .AcmpB                  (AcmpB), 
   .Address_on_Databus     (Address_on_Databus), 
   .AmulB                  (AmulB), 
   .AorB                   (AorB), 
   .AsubB                  (AsubB), 
   .B15to0                 (B15to0), 
   .Creset                 (Creset), 
   .Cset                   (Cset), 
   .EnablePC               (EnablePC), 
   .IR_on_HOpndBus         (IR_on_HOpndBus), 
   .IR_on_LOpndBus         (IR_on_LOpndBus), 
   .IRload                 (IRload), 
   .PCplus1                (PCplus1), 
   .PCplusI                (PCplusI), 
   .RFHwrite               (RFHwrite), 
   .RFLwrite               (RFLwrite), 
   .RFright_on_OpndBus     (RFright_on_OpndBus), 
   .Rd_on_AddressUnitRSide (Rd_on_AddressUnitRSide), 
   .ReadIO                 (ReadIO), 
   .ReadMem                (ReadMem), 
   .ResetPC                (ResetPC), 
   .Rplus0                 (Rplus0), 
   .RplusI                 (RplusI), 
   .Rs_on_AddressUnitRSide (Rs_on_AddressUnitRSide), 
   .SRload                 (SRload), 
   .Shadow                 (Shadow), 
   .WPadd                  (WPadd), 
   .WPreset                (WPreset), 
   .WriteIO                (WriteIO), 
   .WriteMem               (WriteMem), 
   .Zreset                 (Zreset), 
   .Zset                   (Zset), 
   .notB                   (notB), 
   .shlB                   (shlB), 
   .shrB                   (shrB)
); 


endmodule // Sayeh

